name: documentation

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: |
          cd demo/bci-id-translation/
          pip install poetry
          poetry install
          poetry show

      - name: Sphinx build
        run: |
          cd demo/bci-id-translation/
          source "$(poetry env info --path)/bin/activate"
          sphinx-build docs/ docs/_build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: demo/bci-id-translation/docs/_build/
          force_orphan: true
