name: documentation

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up Python 3.14 with uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: '3.14'

      - name: Install dependencies
        run: |
          cd demo/bci-id-translation/
          uv sync --locked --all-extras
          uv tree

      - name: Sphinx build
        run: |
          cd demo/bci-id-translation/
          source .venv/bin/activate
          sphinx-build docs/ docs/_build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: demo/bci-id-translation/docs/_build/
          force_orphan: true
