name: tests

on:
  schedule:
    - cron: "0 3 1 */2 *"  # 03:00 on the first of every second

  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "info"
      tags:
        required: false
        description: "Test scenario tags"
  push:
    branches:
     - master
  pull_request:
    branches:

jobs:
  tests:
    name: Replay ${{ matrix.replay-file }}
    runs-on: ubuntu-latest
    env:
      REPLAY_FILE: ${{ matrix.replay-file }}
    strategy:
      fail-fast: false
      matrix:
        replay-file: [ "stable", "default", "master" ]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Start Docker database
        shell: bash
        run: docker run -d -p 5002:5432 rsundqvist/sakila-preload:postgres

      - name: Install system deps
        shell: bash
        run: |
          pip install poetry --quiet
          poetry install
      - name: Run tests
        shell: bash
        run: |
          echo "REPLAY_FILE=$REPLAY_FILE"
          poetry run pytest --color=yes tests/
          poetry run pip list
